Use SafeConfigParser from ConfigParser
Using attribute 'ExtendedInterpolation' is not compatible for
configparser.
If it is being used from RHEL 7.4 the following exception
is being thrown:
Traceback (most recent call last):
  File "./ovirt-dr", line 145, in <module>
    main(sys.argv[1:])
  File "./ovirt-dr", line 28, in main
    action, conf_file, log_file, log_level = _init_vars(argv)
  File "./ovirt-dr", line 88, in _init_vars
    log_file, log_level = _get_log_conf(conf_file, log_file, log_level)
  File "./ovirt-dr", line 101, in _get_log_conf
    settings._interpolation = configparser.ExtendedInterpolation()
AttributeError: 'module' object has no attribute 'ExtendedInterpolation'

Therefore to make the code compatible for RHEL as well, instead of
using configparser, we use SafeConfigParser from ConfigParser.